
CREATE DATABASE aminfo;
use aminfo;

CREATE TABLE  CLIENTES (
   ID_CLIENTE int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   CLIENTE  varchar(30) NOT NULL,
   IMAGEN_RUTA VARCHAR(30),
   FECHA_CREACION datetime DEFAULT NOW()
);

CREATE TABLE  ROLES  (
   ID_ROL int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   ID_CLIENTE int NOT NULL,
   ROL varchar(25) NOT NULL, 
   FECHA_CREACION DATE,
   FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);
  

CREATE TABLE USUARIOS (
ID_USUARIO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE int NOT NULL,
ID_ROL int NOT NULL,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
CORREO VARCHAR(40),
NICK VARCHAR(25),
PASS VARCHAR(50),
FECHA_GUARDADO datetime DEFAULT NOW(),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);



CREATE TABLE FIRMAS(
  ID_FIRMA int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRMA_RUTA VARCHAR(30)
); 

 

-- AQUÍ SE AGREGA LOS SERVICIOS
CREATE TABLE SERVICIOS(
  ID_SERVICIO int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO INT NOT NULL,
  NOMBRE VARCHAR(30),
  APELLIDO VARCHAR(30),
  CEDULA VARCHAR(30),
  DIRECCION VARCHAR(30),
  CORREO VARCHAR(25),
  DESCRIPCION  TEXT,
  FECHA_GUARDADO datetime DEFAULT NOW(),
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);






